## 행렬
- 행렬(Matrix)는 벡터를 원소로 가지는 2차원 배열이다.
- 행렬은 row와 column이라는 인덱스를 가진다.
- 행렬의 특정 행(열)을 고정하면 행(열)벡터가 된다.

In [2]:
import numpy as np
X = np.array([[1,-2,3],
                              [7,5,0],
                              [-2,-1,2]])

### 행렬의 이해
- 벡터가 공간 상의 한 점이라면, 행렬읜 여러 점을 의미
- 행렬의 행벡터 X_i 는 i번째 데이터를 의미
- 행렬의 X_ij는 i번째 데이터의 j번째 변수값이라는 의미

### 행렬의 연산
- 행렬의 모양이 같으면 덧(뺄)셈이 가능
- 성분곱은 벡터와 같다.
- 스칼라 곱도 차이가없다.
- 행렬의 곱셈(Matrix Multiplication)은 i번째 행 벡터와 j번째 열 벡터의 내적을 성분곱으로 가지는 행렬을 계산

In [4]:
# numpy에서 행렬의 곱은 @ 기호로 표현
X = np.array([[1,-2,3],
                              [7,5,0],
                              [-2,-1,2]])

Y = np.array([[2,-1,4],
                              [3,1,2],
                              [-1,-2,4]])

X@Y

array([[-7, -9, 12],
       [29, -2, 38],
       [-9, -3, -2]])

### 행렬의 내적
- numpy의 np.inner함수는 i번재 행 벡터와 j번째 내적을 성분으로 하는 행렬을 계산한다. 
- 행렬 곱을 통해 벡터를 다른 차원의 공간으로 보낼 수 있다.
- 행렬 곱을 통해 패턴 추출이 가능, 데이터를 압축할 수 도 있다. 모든 선형변환은 (linear Transform) 행렬 곱으로 계산 가능

In [7]:
np.inner(X,Y)

array([[ 16,   7,  15],
       [  9,  26, -17],
       [  5,  -3,  12]])

- 어떤 행렬 A의 연산을 거꾸로 되돌리는 행렬을 역행렬이라 하며 A^-1로 표기한다. 역행렬은 행과열의 숫자가 같고 행렬식이 0이 아닌 경우에 계산이가능하다.

In [17]:
X_inv = np.linalg.inv(X)

X_inv@X

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00,  1.11022302e-16],
       [-1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])

- n != m 이라 역행렬을 계산할 수 없다면 유사 역행렬(=무어펜로즈) 역행렬 A^+를 사용한다.

In [18]:
Y = np.array([[1,2],
                            [2,-1],
                            [0,1]])

Y_pinv = np.linalg.pinv(Y)
Y_pinv@Y

array([[ 1.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00]])

### 응용1. 연립방정식 풀기
- np.linalg.pinv를 이용해 연립방정의 해를 구할 수 있다.

### 응용2. 선형회귀분석
- np.linalg.pinv를 이용해 데이터를 선형모델로 해석하는 선형회귀식을 찾을 수 있음
- sklearn의 LinearRegression도 같은 결과 도출 가능